# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8da5661070365ca69eb343febc96dac7aa0564f273627f9abc0112cddf29ad07499045686f989144d362ed2d506018564a31fc42987585a918f88664b68f56a

test:
  secret_key_base: 8b32d9436a8aabf243ddf251647341b285cef299caf20b3f73c127f68faf4bf3c559b02afc27e1dd0cc17a0cfb00d9ae1663ccc78528ad287cf5add3c9543f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
